name: Build Dev Pulse (daily)

on:
  workflow_dispatch:
  schedule:
    # 12:00 AM UTC daily (8:00 PM EDT currently)
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build pulse JSON
        run: |
          node --version
          node scripts/buildPulse.mjs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit data
        uses: EndBug/add-and-commit@v9
        with:
          author_name: MLD Bot
          author_email: bot@majorleaguedev.com
          message: "chore(data): refresh dev pulse JSON"
          add: "data/repos.json"
