name: Pages (Preview)

on:
  pull_request:
    branches: [ main ]   # run when PRs target main

permissions:
  contents: read
  pages: write           # REQUIRED for deploy-pages
  id-token: write        # REQUIRED for deploy-pages OIDC

concurrency:
  group: pages-preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "."       # your site is static files in repo root

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true   # tells GitHub this is a PR preview
